default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("PGHOST", "127.0.0.1") %>
  port: <%= ENV.fetch("PGPORT", 5432) %>
  username: <%= ENV.fetch("PGUSER", "dermetics") %>
  password: 1234
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: dermetics_development

test:
  <<: *default
  database: dermetics_test

production:
  primary:
    <<: *default
    database: dermetics_production

  cable:
    <<: *default
    database: dermetics_production

  queue:
    <<: *default
    database: dermetics_production

  cache:
    <<: *default
    database: dermetics_production

